#application.yml配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml

  mvc:
    static-path-pattern: /**

  thymeleaf:
    prefix: classpath:/templates #prefix：指定模板所在的目录
    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
    cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
    suffix: .html
    #encoding: UTF-8
    #content-type: text/html
    mode: HTML5


#hdfs的ip+端口  hdfs配置使用
#HDFS_HOSTS: "hdfs:10.178.192.175:9870"
HDFS_HOSTS: "hdfs:172.17.7.12:9870"
#hdfs_seq_dir
hdfsDir: "/UAVVideo/"
HDFS_URL: "172.17.7.12:14000"


#ES
esHostports: 172.17.7.12:9200,172.17.7.13:9200,172.17.7.14:9200
esHost: 172.17.7.12,172.17.7.123.13,172.17.7.14
esport: 9200
esindex: "vstream-ai-service"
estype: "_doc"